[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
debug_tool = stlink

; I2C pins: PB6=SCL, PB7=SDA
build_flags = 
    -D I2C_SDA_PIN=PB7
    -D I2C_SCL_PIN=PB6

lib_deps = 
    paulstoffregen/Wire@^10.0
    adafruit/Adafruit_BME280@^2.1.4
    adafruit/Adafruit_SSD1306@^2.5.0
    adafruit/RTClib@^2.1.1
