; PlatformIO Project Configuration File
; STM32F103C8T6 - Blink LED
; Praktikum 1: LED Berkedip Dasar

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

; Upload menggunakan ST-Link
upload_protocol = stlink

; Debug menggunakan ST-Link
debug_tool = stlink

; Serial Monitor
monitor_speed = 115200

; Build flags
build_flags = 
    -D USE_HAL_DRIVER
    -D STM32F103xB
