[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

build_flags = 
    -D USE_HAL_DRIVER
    -D STM32F103xB
    -D configUSE_TICKLESS_IDLE=1
    -I lib/FreeRTOS/include
    -I lib/FreeRTOS/portable/GCC/ARM_CM3
    -O2

lib_deps = 
    FreeRTOS-Kernel@^10.5.1

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
