; PlatformIO Configuration File
; Modul 12 - ESP32 Program 07: Static Allocation Dual Core
; Target: ESP32 DevKit V1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor
monitor_speed = 115200

build_flags = 
    -D CONFIG_FREERTOS_SUPPORT_STATIC_ALLOCATION=1
