[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
debug_tool = stlink

build_flags = 
    -D LED_BUILTIN=PC13

lib_deps =
    STM32duino DMA
