; PlatformIO Configuration File
; Modul 12 - ESP32 Program 04: Event Groups Advanced
; Target: ESP32 DevKit V1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor
monitor_speed = 115200
