; PlatformIO Project Configuration File
; STM32F103C8T6 - I2C Communication
; Praktikum 8: I2C dengan OLED SSD1306

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

build_flags = 
    -D USE_HAL_DRIVER
    -D STM32F103xB
