; PlatformIO Configuration File
; Modul 12 - ESP32 Program 03: PSRAM Usage
; Target: ESP32 DevKit V1 (dengan PSRAM)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor
monitor_speed = 115200

; Enable PSRAM
build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
